### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by master-davidlee** [Messi-Q/GraphDeeSmartContract#1]
请问您能提供一下全部的源代码和数据集吗 ？您的文章对我们启发很大，我们想要复现实验。谢谢

**Comment by Messi-Q** [comment]
> 请问您能提供一下全部的源代码和数据集吗 ？您的文章对我们启发很大，我们想要复现实验。谢谢

您好，相关的源代码和数据集可以参考 
https://github.com/Messi-Q/GNNSCVulDetector
https://github.com/Messi-Q/Smart-Contract-Dataset
https://github.com/Messi-Q/GraphDeeSmartContract
